# Brews
brew "diff-so-fancy"
brew "git"
brew "gnupg"
brew "mas"
brew "mise"
brew "opencode"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Casks
cask "1password"
cask "1password-cli"
cask "aerial"
cask "appcleaner"
cask "bartender"
cask "claude-code"
cask "codex"
cask "cursor"
cask "discord"
cask "ghostty"
cask "google-chrome"
cask "orbstack"
cask "raycast"
cask "rectangle"
cask "slack"
cask "spotify"
cask "steam"
cask "unity-hub"
cask "visual-studio-code"
cask "zoom"

# App Store
mas "Xcode", id: 497799835
