[settings]
experimental = true
pipx.uvx = true
python.uv_venv_auto = true

[env]
UV_COMPILE_BYTECODE = true

[tools]
awscli = "latest"
helm = "latest"
kubectl = "latest"
k9s = "latest"
python = "3.13"
uv = "latest"

# tools installed with uvx
"pipx:ipython" = { version = "latest", uvx_args = "--with ipdb,ipykernel,numpy" }
"pipx:mypy" = { version = "latest" }
"pipx:pre-commit" = { version = "latest" }
"pipx:ruff" = { version = "latest" }
