[tools]
aws-cli = "latest"
helm = "latest"
kubectl = "latest"
k9s = "latest"
node = "22"
python = "3.13"
uv = "latest"

"pipx:ipython" = { version = "latest", uvx_args = "--with ipdb,ipykernel" }
"pipx:mypy" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"pipx:watchdog" = "latest"

[hooks]
postinstall = [
  "corepack install -g pnpm yarn",
  "corepack enable pnpm yarn",
]

[settings]
experimental = true
pipx.uvx = true
python.uv_venv_auto = true

[env]
MISE_NODE_COREPACK = true
UV_COMPILE_BYTECODE = true
