[tools]
aws-cli = "latest"
bun = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
node = "lts"
python = "3.14"
usage = "latest"
uv = "latest"

"pipx:ipython" = { version = "latest", uvx_args = "--with ipdb,ipykernel" }

[settings]
activate_aggressive = true
env_shell_expand = true
exec_auto_install = true
experimental = true
minimum_release_age = "7d"
not_found_auto_install = true
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "create|source"
task.run_auto_install = true
trusted_config_paths = ["~/.config/mise", "~/Workspace"]

[env]
UV_COMPILE_BYTECODE = true
